Git homework
ibra86/common pull request #1
Opened 2019-09-26 06:17 UTC by ibra86

PR

2019-09-26 22:51 UTC, klimach approved these changes

2019-09-27 11:01 UTC, ekut2104 requested changes
Код написаний вірно. Та є правила хорошого написання коду, аби він був читабельний і зрозуміліший.
Для цього Гвідо зробив гайд https://www.python.org/dev/peps/pep-0008/
Тож маємо поважати його побажання.
Тим більше що PyCharm вказує нам завжи ці нюанси.

2019-09-27 11:01 UTC, ekut2104 commented on git/homework.py
> +    if (not isinstance(first_value,int)) or (not isinstance(second_value,int)):
PEP8 пропущений пробіл  після коми)

2019-09-27 11:01 UTC, ekut2104 commented on git/homework.py
`    except:
        raise(ValueError)`
в ексепт треба додати очікуваний тип помилки, raise ValueError без дужок мало б бути)

2019-09-27 11:01 UTC, ekut2104 commented on git/homework.py
За PEP8 тут, між цими функціями, мало б бути дві пусті лінії.

2019-09-27 11:01 UTC, ekut2104 commented on git/homework.py
> +    for i,x in enumerate(data):
`    for i,x in enumerate(data):`
пробіл після коми

2019-09-27 11:01 UTC, ekut2104 commented on git/homework.py
пробіл після коми та двокрапки

2019-09-29 21:20 UTC, merged