hw_06 is done, tests are passed
ibra86/common pull request #12
Opened 2019-10-15 04:07 UTC by ibra86

2019-10-16 18:08 UTC, pavlozubariev requested changes

2019-10-16 18:08 UTC, pavlozubariev commented on oop/homework.py
> +            self._increase_saturation_level(sat_lvl)
products_sat_lvls можна записати словником, пошук по словнику простіший

2019-10-16 18:08 UTC, pavlozubariev commented on oop/homework.py
> +        return average_speed
Тернарна операція з кількома if складна для читання, якщо виходь щось більше ніж наприклад average_speed = 12 if self.age <= 7 else 9, то краще використати класичну if ... elif ... else конструкцію

2019-10-16 18:08 UTC, pavlozubariev commented on oop/homework.py
> +                        50
теж складна для читання тернарна операція

2019-10-16 18:08 UTC, pavlozubariev commented on oop/homework.py
> +            self._increase_saturation_level(sat_lvl)
products_sat_lvls можна записати в словник

2019-10-16 18:08 UTC, pavlozubariev commented on oop/homework.py
> +        return average_speed
складна для читання тернатна операція

2019-10-16 21:29 UTC, ibra86 commented on oop/homework.py
> +            self._increase_saturation_level(sat_lvl)
простійший в якому сенсі? швидший? чи зручніший?

2019-10-17 17:23 UTC, pavlozub85 commented on oop/homework.py
> +            self._increase_saturation_level(sat_lvl)
і швидший і зручніший завдяким вбудованим методам

2019-10-17 17:30 UTC, pavlozubariev approved these changes

2019-10-24 18:31 UTC, merged